// eslint.config.js
import js from '@eslint/js';
import globals from 'globals';

export default [
  js.configs.recommended,
  {
    languageOptions: {
      globals: {
        ...globals.browser,
        chrome: 'readonly',
        AbortSignal: 'readonly',
        // COMMENT: Globals shared between content.js, content.shared.js, content.styles.js
        SELECTORS: 'readonly',
        THEME_COLORS: 'readonly',
        UI_STYLES: 'readonly',
        PROMPT_CLOSE_DELAY: 'readonly',
        HIDE_ANIMATION_MS: 'readonly',
        MUTATION_DEBOUNCE_MS: 'readonly',
        SEARCH_FOCUS_DELAY_MS: 'readonly',
        ONBOARDING_AUTO_HIDE_MS: 'readonly',
        ONBOARDING_FADE_OUT_MS: 'readonly',
        IMPORT_SUCCESS_RESET_MS: 'readonly',
        SCROLLBAR_PERSIST_MS: 'readonly',
        HOT_CORNER_INDICATOR_SMALL_PX: 'readonly',
        HOT_CORNER_INDICATOR_LARGE_PX: 'readonly',
        ChromeBridge: 'readonly',
        createEl: 'readonly',
        debounce: 'readonly',
        getMode: 'readonly',
        getIconFilter: 'readonly',
        showEl: 'readonly',
        hideEl: 'readonly',
        Theme: 'readonly',
        $root: 'readonly',
        qs: 'readonly',
        PanelView: 'readonly',
        PanelRouter: 'readonly',
        ScrollVisibilityManager: 'readonly',
        OutsideClickCloser: 'readonly',
        KeyboardManager: 'readonly',
        EventBus: 'readonly',
        PromptStorageManager: 'readonly',
        PromptUIManager: 'writable',
        PromptProcessor: 'readonly',
        PromptMediator: 'readonly',
        isDarkMode: 'readonly',
        isDarkModeActive: 'writable',
        ensureStylesInjected: 'readonly',
        injectGlobalStyles: 'readonly',
        TagService: 'readonly',
        TagUI: 'readonly',
        PromptUI: 'readonly',
        InputBoxHandler: 'readonly',
      },
      ecmaVersion: 2022,
      sourceType: 'module',
    },
    rules: {
      'no-unused-vars': ['warn', { argsIgnorePattern: '^_', varsIgnorePattern: '^_' }],
      'no-console': 'off',
      'no-constant-condition': 'off',
      'no-empty': 'warn',
      'semi': ['error', 'always'],
      'quotes': ['error', 'single', { avoidEscape: true }],
      'no-var': 'error',
      'prefer-const': 'warn',
      'eqeqeq': ['error', 'always', { null: 'ignore' }],
    },
  },
  {
    ignores: ['tests/**', '*.test.js'],
  },
];
